version: '3.8'

services:
  nest-app:
    build: .
    container_name: pho-app
    ports:
    - "27017:27017"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/pho-app
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
